package scan

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/backendArchitect/gospect-mcp/internal/detect"
)

func TestDropGenerated(t *testing.T) {
	dir := t.TempDir()
	gen := filepath.Join(dir, "gen.go")
	hand := filepath.Join(dir, "hand.go")
	// Marker must precede real code; here it's the first line.
	write(t, gen, "// Code generated by stringer. DO NOT EDIT.\n\npackage p\n")
	write(t, hand, "package p\n\n// Code generated ... DO NOT EDIT. (too late — real code came first)\n")

	kept, dropped := dropGenerated([]detect.Finding{
		{File: gen, Line: 3, Detector: "nilness"},
		{File: hand, Line: 1, Detector: "nilness"},
	})
	if dropped != 1 || len(kept) != 1 || kept[0].File != hand {
		t.Fatalf("dropped=%d kept=%d; want 1 dropped, hand.go kept", dropped, len(kept))
	}
}

func TestIsGeneratedFile_MarkerAfterCode(t *testing.T) {
	dir := t.TempDir()
	f := filepath.Join(dir, "x.go")
	// The marker appears only after the package clause -> NOT generated by the convention.
	write(t, f, "package p\nvar x = 1 // Code generated foo DO NOT EDIT.\n")
	if isGeneratedFile(f) {
		t.Fatal("marker after real code must not count as generated")
	}
}

func write(t *testing.T, path, body string) {
	t.Helper()
	if err := os.WriteFile(path, []byte(body), 0o644); err != nil {
		t.Fatal(err)
	}
}
